POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "usuario",
  "email": "test@win.com",
  "contrasenia": "password123",
  "telefono": "123456789",
  "pin": "1234"
}
###
PUT http://localhost:3000/usuarios/4
Content-Type: application/json

{
  "name": "usuario",
  "email": "test@gmail.com",
  "password": "password123",
  "phoneNumber": "123456789",
  "pin": "1234"
}

###

POST http://localhost:3000/contactos
Content-Type: application/json

{
  "name": "contacto",
  "phoneNumber": "987654321",
  "userId": 1,
  "priority": 1
}
###
GET http://localhost:3000/usuarios/4/contactos
###
GET http://localhost:3000/contactos/1
###
PUT http://localhost:3000/contactos/5
Content-Type: application/json

{
  "name": "CEO",
  "phoneNumber": "987654321",
  "userId": 4,
  "priority": 1
}
###
DELETE http://localhost:3000/contactos/1
###
POST http://localhost:3000/trayectos
Content-Type: application/json

{
  "usuario_id": 1,
  "nombre": "trayecto1",
  "inilat": 40.4168,
    "inilon": -3.7038,
    "destlat": 40.7128,
    "destlon": -74.0060,
    "ruta": "ruta1",
    "estado": "en progreso"

}
###
GET http://localhost:3000/trayectos/2/estado
###
PATCH http://localhost:3000/trayectos/2
Content-Type: application/json

{
  "estado": "finalizado"
}
###
POST http://localhost:3000/trayectos/2/posiciones
Content-Type: application/json

{
  "latitud": 40.730610,
  "longitud": -79.935242
}
###
GET http://localhost:3000/trayectos/2/posiciones
###
POST http://localhost:3000/trayectos/1/alertas
Content-Type: application/json

{
  "descripcion": "Alerta de detención",
  "descripcion": "El usuario se ha detenido inesperadamente.",
  "tipo": "detencion",
  "lat": 40.730610,
  "lon": -79.935242
}












###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "cifrado"
}
###
POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "password": "cifrado",
  "phoneNumber": "123456789",
  "pin": "1234"
}

###
GET http://localhost:3000/contactos/1
###
PUT http://localhost:3000/contacts/update/5
Content-Type: application/json

{
  "name": "CEO",
  "phoneNumber": "987654321",
  "userId": 4,
  "priority": 1
}
###
DELETE http://localhost:3000/contacts/delete/7

###
POST http://localhost:3000/trips
Content-Type: application/json

{
  "userid": 1,
  "name": "trayecto1",
  "inilat": 40.4168,
    "inilon": -3.7038,
    "destlat": 40.7128,
    "destlon": -74.0060,
    "route": "ruta1",
    "status": "en progreso"

}

###
POST http://localhost:3000/trips/newtrip
Content-Type: application/json

{
  "userid": 1,
  "name": "trayecto1",
 "inilat": 40.4168,
  "inilon": -3.7038,
  "destlat": 40.9429,
  "destlon": -4.1088,
    "status": "en progreso"

}